package io.hedwig.ignitops.entity;

import java.io.Serializable;

/**
 * Car definition.
 * 
 * This file was generated by Ignite Web Console (07/11/2017, 08:53)
 **/
public class Car implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for parkingId. */
    private int parkingId;

    /** Value for name. */
    private String name;

    /**
     * Gets parkingId
     * 
     * @return Value for parkingId.
     **/
    public int getParkingId() {
        return parkingId;
    }

    /**
     * Sets parkingId
     * 
     * @param parkingId New value for parkingId.
     **/
    public void setParkingId(int parkingId) {
        this.parkingId = parkingId;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Car))
            return false;
        
        Car that = (Car)o;

        if (parkingId != that.parkingId)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = parkingId;

        res = 31 * res + (name != null ? name.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Car [" + 
            "parkingId=" + parkingId + ", " + 
            "name=" + name +
        "]";
    }
}