package io.hedwig.ignitops.entity;

import java.io.Serializable;

/**
 * Country definition.
 * 
 * This file was generated by Ignite Web Console (07/11/2017, 08:53)
 **/
public class Country implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for name. */
    private String name;

    /** Value for population. */
    private int population;

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets population
     * 
     * @return Value for population.
     **/
    public int getPopulation() {
        return population;
    }

    /**
     * Sets population
     * 
     * @param population New value for population.
     **/
    public void setPopulation(int population) {
        this.population = population;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Country))
            return false;
        
        Country that = (Country)o;

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (population != that.population)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = name != null ? name.hashCode() : 0;

        res = 31 * res + (population);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Country [" + 
            "name=" + name + ", " + 
            "population=" + population +
        "]";
    }
}