package io.hedwig.ignitops.entity;

import java.io.Serializable;

/**
 * Department definition.
 * 
 * This file was generated by Ignite Web Console (07/11/2017, 08:53)
 **/
public class Department implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for countryId. */
    private int countryId;

    /** Value for name. */
    private String name;

    /**
     * Gets countryId
     * 
     * @return Value for countryId.
     **/
    public int getCountryId() {
        return countryId;
    }

    /**
     * Sets countryId
     * 
     * @param countryId New value for countryId.
     **/
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Department))
            return false;
        
        Department that = (Department)o;

        if (countryId != that.countryId)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = countryId;

        res = 31 * res + (name != null ? name.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Department [" + 
            "countryId=" + countryId + ", " + 
            "name=" + name +
        "]";
    }
}